apiVersion:  apps/v1
kind:  Deployment
metadata:
  name:  backend-deployment
  labels:
    app:  backend-deploy
spec:
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name:  backend-container
        image:  vijetaagrawal/backend:latest
        ports:
        - containerPort:  9001
        env:
        - name:  DATABASE_URL
          value:  "prod-rds.csqfw1gtm6ou.eu-west-1.rds.amazonaws.com:3306"
  replicas:  5
  selector:
    matchLabels:
      app:  backend