apiVersion:  apps/v1
kind:  Deployment
metadata:
  name:  frontend-deployment
  labels:
    app:  frontend-deploy
spec:
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name:  frontend-container
        image:  vijetaagrawal/frontend:latest
        ports:
        - containerPort:  3000
  replicas:  5
  selector:
    matchLabels:
      app:  frontend